### ISSUE TITLE
Cohort Re-Authetication

### ISSUE THREAD

**Issue by groovetemple** [frumbert/wp2moodle-moodle#8] opened 2014-04-16 00:12 UTC
Hey there, seems to be working great for me, however, one issue when re-authenticating after user has already been created, upon logging back in Moodle directs the user to edit profile page again instead of bypassing this and going straight course..  Any thoughts?

**Comment by frumbert** [comment] 2015-01-15 23:01
Not sure what the issue is here - it's working on my installations. The code is taking the courseid directly from the related record; in case of cohorts, this is:

    if ($enrolrow = $DB->get_record('enrol', array('enrol'=>'cohort','customint1'=>$cohortrow->id,'status'=>0))) {
        $SESSION->wantsurl = new moodle_url('/course/view.php', array('id'=>$enrolrow->courseid));
    }

However it then repeats the code for groups. If you have specified both group and cohort, then it will take the groups' course in preference (because of the order of the code). This is the only scenario I can come up with that might cause the issue.

Since I can't create the problem myself, I'm closing the issue for now.

**Closed by frumbert** 2015-01-15 23:01 UTC
